import { writable, readable } from 'svelte/store';

export const parsedData = writable([]);

export const selectedCounty = writable('Los Angeles');

export const countyList = readable([
    ['Alameda', 'alameda'],
    ['Alpine', 'alpine'],
    ['Amador', 'amador'],
    ['Butte', 'butte'],
    ['Calaveras', 'calaveras'],
    ['Colusa', 'colusa'],
    ['Contra Costa', 'contra-costa'],
    ['Del Norte', 'del-norte'],
    ['El Dorado', 'el-dorado'],
    ['Fresno', 'fresno'],
    ['Glenn', 'glenn'],
    ['Humboldt', 'humboldt'],
    ['Imperial', 'imperial'],
    ['Inyo', 'inyo'],
    ['Kern', 'kern'],
    ['Kings', 'kings'],
    ['Lake', 'lake'],
    ['Lassen', 'lassen'],
    ['Los Angeles', 'los-angeles'],
    ['Madera', 'madera'],
    ['Marin', 'marin'],
    ['Mariposa', 'mariposa'],
    ['Mendocino', 'mendocino'],
    ['Merced', 'merced'],
    ['Modoc', 'modoc'],
    ['Mono', 'mono'],
    ['Monterey', 'monterey'],
    ['Napa', 'napa'],
    ['Nevada', 'nevada'],
    ['Orange', 'orange'],
    ['Placer', 'placer'],
    ['Plumas', 'plumas'],
    ['Riverside', 'riverside'],
    ['Sacramento', 'sacramento'],
    ['San Benito', 'san-benito'],
    ['San Bernardino', 'san-bernardino'],
    ['San Diego', 'san-diego'],
    ['San Francisco', 'san-francisco'],
    ['San Joaquin', 'san-joaquin'],
    ['San Luis Obispo', 'san-luis-obispo'],
    ['San Mateo', 'san-mateo'],
    ['Santa Barbara', 'santa-barbara'],
    ['Santa Clara', 'santa-clara'],
    ['Santa Cruz', 'santa-cruz'],
    ['Shasta', 'shasta'],
    ['Sierra', 'sierra'],
    ['Siskiyou', 'siskiyou'],
    ['Solano', 'solano'],
    ['Sonoma', 'sonoma'],
    ['Stanislaus', 'stanislaus'],
    ['Sutter', 'sutter'],
    ['Tehama', 'tehama'],
    ['Trinity', 'trinity'],
    ['Tulare', 'tulare'],
    ['Tuolumne', 'tuolumne'],
    ['Ventura', 'ventura'],
    ['Yolo', 'yolo'],
    ['Yuba', 'yuba']
]);